from typing import Any, Callable, TypeVar

T = TypeVar("T")

class Request:
    state: Any

class Response: ...

class HTTPException(Exception):
    def __init__(self, status_code: int, detail: str | None = None) -> None: ...

class _Status:
    HTTP_401_UNAUTHORIZED: int
    HTTP_403_FORBIDDEN: int

status: _Status

class APIRouter:
    def __init__(self, prefix: str = ..., tags: list[str] | None = ...) -> None: ...
    def get(self, path: str, response_model: Any = ...) -> Callable[[T], T]: ...
    def post(self, path: str, response_model: Any = ...) -> Callable[[T], T]: ...

class FastAPI:
    def __init__(self, title: str = ..., version: str = ...) -> None: ...
    def include_router(self, router: APIRouter) -> None: ...
    def on_event(self, event_type: str) -> Callable[[T], T]: ...
    def middleware(self, middleware_type: str) -> Callable[[T], T]: ...
    def get(self, path: str) -> Callable[[T], T]: ...


def Depends(dependency: Any = ...) -> Any: ...
def Query(default: Any = ...) -> Any: ...
