"use client";

import { createContext, useContext, useState, ReactNode } from "react";

export type Language = "fr" | "en" | "es";

export const translations = {
  fr: {
    // Navigation
    nav_dashboard: "accueil",
    nav_profile: "profil",
    nav_menu: "menu",
    nav_subscription: "abonnement",
    nav_journal: "journal",
    nav_widgets: "widgets",

    // Dashboard
    petals: "pétales",
    build_mode: "mode encrage",
    quit_mode: "mode sevrage",
    build_tagline: "construis",
    quit_tagline: "libère-toi",
    streak_days: "jours de série",
    freed_days: "jours libérés",
    hi_user: "Salut, {{name}}",
    dashboard_tagline: "Cultivons tes habitudes ensemble !",
    dashboard_quote: "Très beau parcours. Ton effort est légendaire !",
    dashboard_suggested: "Suggéré pour toi",
    dashboard_created_title: "Habitudes",
    dashboard_created_label: "créées",
    dashboard_build_count_title: "Encrage",
    dashboard_build_count_label: "habitudes",
    dashboard_recent_title: "Habitudes récentes",
    daily_goals_title: "Tes objectifs du jour sont presque atteints ! 🔥",
    daily_goals_subtitle: "{{completed}} sur {{total}} complétés",
    habits_title: "Habitudes",
    view_all: "Voir tout",
    show_less: "Réduire",
    habit_done: "Fait pour aujourd'hui !",
    habit_not_started: "Pas encore commencé",
    no_habits_yet: "Pas encore d'habitudes. Commence petit !",
    create_habit_cta: "+ Créer une habitude",
    done_today: "✓ fait aujourd'hui",
    freed_day: "✓ jour réussi",
    add_habit: "+ ajouter une habitude",
    no_build_habits: "aucune habitude en construction",
    no_quit_habits: "aucune habitude à quitter pour l'instant",
    swipe_build: "← swipe pour voir le mode encrage →",
    swipe_quit: "← swipe pour voir le mode sevrage",

    // Profile
    profile_title: "profil & historique",
    your_journey: "ton parcours bloom",
    member_since: "membre depuis mai 2026",
    active_habits: "habitudes actives",
    total_days: "jours totaux",
    petals_count: "pétales",
    year_activity: "activité de l'année",
    less: "moins",
    more: "plus",
    insights: "insights",
    longest_streak: "plus longue série",
    best_day: "meilleur jour",
    best_habit: "habitude la plus réussie",
    data_note: "💜 toutes tes données sont conservées avec bienveillance. même les jours manqués restent visibles pour t'aider à comprendre ton parcours.",
    days_label: ["l", "m", "m", "j", "v", "s", "d"],
    months_label: ["jan", "fév", "mar", "avr", "mai", "jun", "jul", "aoû", "sep", "oct", "nov", "déc"],

    // Settings
    settings_title: "paramètres",
    appearance: "apparence",
    appearance_desc: "thèmes, sons et animations",
    theme_system: "système",
    custom_colors: "couleurs personnalisées",
    primary_color: "couleur principale",
    background_color: "arrière-plan",
    text_color: "texte",
    dark_mode: "mode sombre",
    dark_mode_on: "deep night activé",
    dark_mode_off: "sunbeam cream activé",
    forest: "forêt",
    ocean: "océan",
    sound_effects: "effets sonores",
    sound_effects_on_label: "activés",
    sound_effects_off_label: "désactivés",
    animations: "animations",
    animations_on_label: "activées",
    animations_off_label: "désactivées",
    notifications: "notifications",
    notif_examples: "exemples de rappels bienveillants :",
    integrations: "intégrations",
    gcal: "Google Calendar",
    gcal_desc: "synchronise tes habitudes avec ton calendrier",
    account: "compte",
    manage_sub: "gérer l'abonnement",
    manage_sub_desc: "version seedling (gratuite)",
    export_data: "exporter mes données",
    export_data_desc: "télécharge ton historique",
    about: "À propos de bloom",
    version: "version 1.0.0",
    support: "support",
    help_center: "centre d'aide",
    contact_us: "nous contacter",
    privacy: "politique de confidentialité",
    language: "langue",
    footer: "fait avec 💛 par l'équipe bloom",
    bloom_premium: "bloom premium",
    premium_desc: "habitudes illimitées • 7 émotions de sunny • zéro pub",
    discover: "découvrir bloom",

    // Journal
    journal_title: "journal intime",
    journal_subtitle: "tes pensées, ton espace",
    new_entry: "nouvelle entrée",
    today: "aujourd'hui",
    how_feeling: "comment tu te sens aujourd'hui ?",
    write_placeholder: "écris ici... sans pression, sans jugement.",
    save_entry: "enregistrer",
    entries: "entrées",
    no_entries: "pas encore d'entrées. commence à écrire 🌱",

    // Widgets
    widgets_title: "widgets",
    widgets_subtitle: "personnalise ton expérience",
    streak_widget: "widget série",
    streak_widget_desc: "affiche ta série quotidienne",
    heatmap_widget: "widget heatmap",
    heatmap_widget_desc: "aperçu de ton activité",
    sunny_widget: "widget sunny",
    sunny_widget_desc: "sunny sur ton écran d'accueil",
    add_widget: "ajouter",
    added: "ajouté ✓",
    coming_soon: "disponible bientôt",
    tutorial_step1: "Salut, moi c'est Sunny. En 30 secondes, je te montre les zones clés.",
    tutorial_step2: "Ici, tu vois tes pétales: chaque check-in les fait grandir.",
    tutorial_step3: "Dans cette zone, tu retrouves tes habitudes à faire aujourd'hui.",
    tutorial_step4: "Ce switch te laisse changer vite entre mode encrage et mode sevrage.",
    tutorial_step5: "Cette barre t'ouvre le profil, le journal, les widgets et plus encore.",
    tutorial_step6: "Parfait. On commence petit aujourd'hui, et on continue demain.",

    // Common
    back: "retour",
    save: "enregistrer",
    cancel: "annuler",
    close: "fermer",

    // Onboarding
    onboarding_brand_step: "premier pas",
    onboarding_consent_title: "Ta vie privée, notre priorité.",
    onboarding_consent_subtitle: "Pour t'offrir la meilleure expérience Bloom, nous avons besoin de collecter quelques données de manière anonyme.",
    onboarding_consent_cta: "J'accepte et je continue",
    onboarding_consent_footer: "En continuant, tu acceptes nos Conditions d'utilisation et notre Politique de confidentialité.",

    onboarding_welcome_hi_sunny: "Salut, je suis Sunny ! 🌻",
    onboarding_welcome_subtext: "Je suis si heureux que tu sois là. Cultivons quelque chose de bien ensemble, une petite habitude à la fois.",
    onboarding_welcome_cta: "C'est parti ! →",
    onboarding_welcome_already_account: "J'ai déjà un compte ?",
    onboarding_welcome_signin: "Se connecter",

    onboarding_auth_title: "Préparons ton arrivée",
    onboarding_auth_subtitle: "Choisis comment tu souhaites continuer. Cela ne prend qu'un instant.",
    onboarding_auth_apple: "Continuer avec Apple",
    onboarding_auth_google: "Continuer avec Google",
    onboarding_auth_facebook: "Continuer avec Facebook",
    onboarding_auth_email: "Continuer avec Email",
    onboarding_auth_sso: "Continuer avec SSO",
    onboarding_auth_footer: "Tu as déjà un compte ?",
    onboarding_auth_login: "Se connecter",
    onboarding_auth_safe: "Tes infos sont en sécurité avec moi. 💛",

    login_title: "Connexion",
    login_email_placeholder: "Email",
    login_password_placeholder: "Mot de passe",
    login_cta: "Se connecter",
    login_forgot_password: "Mot de passe oublié ?",
    login_privacy_terms: "En continuant, tu acceptes les Conditions d'utilisation et la Politique de confidentialité de Bloom.",

    signup_title: "Je crée mon compte",
    signup_password_placeholder: "Mot de passe",
    signup_confirm_password_placeholder: "Confirmer le mot de passe",
    signup_cta: "Enregistrer",
    signup_consent_error: "Tu dois accepter les conditions pour continuer.",

    survey_step1_title: "Trouvons ton Bloom",
    survey_step2_title: "Par quel type d'habitude veux-tu commencer ?",
    survey_step3_title: "À quelle fréquence veux-tu suivre cette habitude ?",
    survey_step1_sub: "Quelques questions rapides pour que je puisse te guider au mieux.",
    survey_step2_sub: "Tu pourras toujours ajouter l'autre plus tard.",
    survey_step3_sub: "Choisis ce qui te semble réalisable, la régularité bat la précocité.",
    survey_step1_quote: "Peu importe ce qui t'amène ici, c'est une excellente raison.",
    survey_step2_quote: "Un nouveau départ t'attend !",
    survey_step3_quote: "Les petits pas mènent à de grandes floraisons !",
    survey_option_build_habits: "Créer de meilleures habitudes",
    survey_option_break_habit: "Se libérer d'une habitude",
    survey_option_control: "Me sentir plus en contrôle",
    survey_option_explore: "Juste explorer Bloom",
    survey_option_build_mode: "Créer une bonne habitude (Mode Vert)",
    survey_option_quit_mode: "Arrêter une mauvaise habitude (Mode Mauve)",
    survey_option_both: "Un peu des deux",
    survey_option_daily: "Quotidien",
    survey_option_often: "Quelques fois par semaine",
    survey_option_weekly: "Hebdomadaire",
    survey_option_unsure: "Je ne sais pas encore",

    success_title: "Tu es prêt !",
    success_subtext: "Ton premier tableau de bord est prêt. Faisons le premier pas, ensemble.",
    success_cta: "Entrer dans Bloom →",

    onboarding_intro_title: "Hello!",
    onboarding_intro_subtitle1: "Je m'appelle Sunny bloom.",
    onboarding_intro_subtitle2: "Une expérience douce pour suivre tes habitudes, te célébrer et avancer à ton rythme.",
    onboarding_intro_cta: "Je commence doucement",
    onboarding_welcome_title: "hello, je m'appelle sunny bloom.",
    onboarding_welcome_subtitle: "Une expérience douce pour suivre tes habitudes, te célébrer et avancer à ton rythme, sans pression.",
    onboarding_mode_title: "on te connaît un peu mieux",
    onboarding_mode_subtitle: "quelques questions rapides pour te proposer le bon mode dès le début.",
    onboarding_mode_question1: "Tu veux surtout...",
    onboarding_mode_question2: "Le plus simple pour toi, c'est...",
    onboarding_mode_suggestion: "Notre suggestion",
    onboarding_continue: "continuer",
    onboarding_create_title: "crée ta première habitude",
    onboarding_create_cta: "créer et commencer",
    onboarding_back: "retour",
    onboarding_mode_build: "Construire",
    onboarding_mode_quit: "Sevrer",
    onboarding_mode_guided: "Assisté",
    onboarding_mode_both: "Les deux",
    onboarding_mode_build_desc: "de nouvelles habitudes",
    onboarding_mode_quit_desc: "des mauvaises habitudes",
    onboarding_mode_guided_desc: "un départ doux",
    onboarding_mode_both_desc: "selon les jours",
    onboarding_focus_small: "Petit pas",
    onboarding_focus_daily: "Tous les jours",
    onboarding_focus_weekly: "Par semaine",
    onboarding_focus_small_desc: "1 action à la fois",
    onboarding_focus_daily_desc: "une routine régulière",
    onboarding_focus_weekly_desc: "des objectifs plus larges",
    onboarding_suggest_guided: "Mode assisté",
    onboarding_suggest_quit: "Mode sevrage",
    onboarding_suggest_build: "Mode encrage",
    onboarding_suggest_small: "On commence léger, avec une seule priorité.",
    onboarding_suggest_daily: "On pose une routine simple à reproduire chaque jour.",
    onboarding_suggest_weekly: "On garde des objectifs plus larges, à suivre chaque semaine.",

    // Calendar sync
    calendar_sync_title: "synchronisation calendrier",
    calendar_sync_connected: "connecté",
    calendar_sync_disconnected: "non connecté",
    calendar_sync_connecting: "connexion en cours...",
    calendar_sync_connect_google: "connecter avec Google",
    calendar_sync_auto_label: "synchronisation automatique",
    calendar_sync_auto_desc: "ajoute tes habitudes à Google Calendar",
    calendar_sync_last: "dernière synchro",
    calendar_sync_now: "synchroniser maintenant",
    calendar_sync_disconnect: "déconnecter",

    // About
    about_title: "À propos de Bloom",
    about_mission_title: "Notre Mission",
    about_mission_text: "Chez Bloom, notre mission est de vous aider à cultiver des habitudes saines et à vous épanouir jour après jour. Nous croyons que de petits pas constants mènent à de grandes transformations.",
    about_version_title: "Version de l'application",

    // Journal mood labels
    mood_radiant: "radieux",
    mood_good: "bien",
    mood_neutral: "neutre",
    mood_hard: "difficile",
    mood_tough: "dur",
  },

  en: {
    // Navigation
    nav_dashboard: "home",
    nav_profile: "profile",
    nav_menu: "menu",
    nav_subscription: "subscription",
    nav_journal: "journal",
    nav_widgets: "widgets",

    // Dashboard
    petals: "petals",
    build_mode: "build mode",
    quit_mode: "quit mode",
    build_tagline: "build",
    quit_tagline: "break free",
    streak_days: "day streak",
    freed_days: "days free",
    hi_user: "Hi, {{name}}",
    dashboard_tagline: "Let's make habits together!",
    dashboard_quote: "Great journey. Your effort is legendary!",
    dashboard_suggested: "Suggested for You",
    dashboard_created_title: "Habits",
    dashboard_created_label: "created",
    dashboard_build_count_title: "Build",
    dashboard_build_count_label: "habits",
    dashboard_recent_title: "Recent Habits",
    daily_goals_title: "Your daily goals almost done! 🔥",
    daily_goals_subtitle: "{{completed}} of {{total}} completed",
    habits_title: "Habits",
    view_all: "View All",
    show_less: "Show Less",
    habit_done: "Done for today!",
    habit_not_started: "Not started yet",
    no_habits_yet: "No habits yet. Start small!",
    create_habit_cta: "+ Create a habit",
    done_today: "✓ done today",
    freed_day: "✓ free day",
    add_habit: "+ add a habit",
    no_build_habits: "no habits being built yet",
    no_quit_habits: "no habits to quit for now",
    swipe_build: "← swipe to see build mode →",
    swipe_quit: "← swipe to see quit mode",

    // Profile
    profile_title: "profile & history",
    your_journey: "your bloom journey",
    member_since: "member since May 2026",
    active_habits: "active habits",
    total_days: "total days",
    petals_count: "petals",
    year_activity: "year activity",
    less: "less",
    more: "more",
    insights: "insights",
    longest_streak: "longest streak",
    best_day: "best day",
    best_habit: "most successful habit",
    data_note: "💜 all your data is kept with care. even missed days stay visible to help you understand your journey.",
    days_label: ["m", "t", "w", "t", "f", "s", "s"],
    months_label: ["jan", "feb", "mar", "apr", "may", "jun", "jul", "aug", "sep", "oct", "nov", "dec"],

    // Settings
    settings_title: "settings",
    appearance: "appearance",
    appearance_desc: "themes, sounds and animations",
    theme_system: "system",
    custom_colors: "custom colors",
    primary_color: "primary color",
    background_color: "background",
    text_color: "text",
    dark_mode: "dark mode",
    dark_mode_on: "deep night enabled",
    dark_mode_off: "sunbeam cream enabled",
    forest: "forest",
    ocean: "ocean",
    sound_effects: "sound effects",
    sound_effects_on_label: "on",
    sound_effects_off_label: "off",
    animations: "animations",
    animations_on_label: "on",
    animations_off_label: "off",
    notifications: "notifications",
    notif_examples: "examples of gentle reminders:",
    integrations: "integrations",
    gcal: "Google Calendar",
    gcal_desc: "sync your habits with your calendar",
    account: "account",
    manage_sub: "manage subscription",
    manage_sub_desc: "seedling version (free)",
    export_data: "export my data",
    export_data_desc: "download your history",
    about: "about bloom",
    version: "version 1.0.0",
    support: "support",
    help_center: "help center",
    contact_us: "contact us",
    privacy: "privacy policy",
    language: "language",
    footer: "made with 💛 by the bloom team",
    bloom_premium: "bloom premium",
    premium_desc: "unlimited habits • 7 sunny emotions • zero ads",
    discover: "discover bloom",

    // Journal
    journal_title: "personal journal",
    journal_subtitle: "your thoughts, your space",
    new_entry: "new entry",
    today: "today",
    how_feeling: "how are you feeling today?",
    write_placeholder: "write here... no pressure, no judgment.",
    save_entry: "save",
    entries: "entries",
    no_entries: "no entries yet. start writing 🌱",

    // Widgets
    widgets_title: "widgets",
    widgets_subtitle: "customize your experience",
    streak_widget: "streak widget",
    streak_widget_desc: "shows your daily streak",
    heatmap_widget: "heatmap widget",
    heatmap_widget_desc: "activity overview",
    sunny_widget: "sunny widget",
    sunny_widget_desc: "sunny on your home screen",
    add_widget: "add",
    added: "added ✓",
    coming_soon: "coming soon",
    tutorial_step1: "Hi, I am Sunny. In 30 seconds, I will show your key zones.",
    tutorial_step2: "This is your petal counter. Every check-in helps it grow.",
    tutorial_step3: "This area holds the habits you are doing today.",
    tutorial_step4: "Use this switch to jump between build and quit mode.",
    tutorial_step5: "This bar opens profile, journal, widgets, and more.",
    tutorial_step6: "Perfect. Start small today, stay steady tomorrow.",

    // Common
    back: "back",
    save: "save",
    cancel: "cancel",
    close: "close",

    // Onboarding
    onboarding_brand_step: "first step",
    onboarding_consent_title: "Your privacy, our priority.",
    onboarding_consent_subtitle: "To offer you the best Bloom experience, we need to collect some anonymous data.",
    onboarding_consent_cta: "I accept and continue",
    onboarding_consent_footer: "By continuing, you agree to Bloom's Terms of Service and Privacy Policy.",

    onboarding_welcome_hi_sunny: "Hi, I'm Sunny! 🌻",
    onboarding_welcome_subtext: "I'm so glad you're here. Let's grow something good together, one small habit at a time.",
    onboarding_welcome_cta: "Let's Bloom →",
    onboarding_welcome_already_account: "Already have an account?",
    onboarding_welcome_signin: "Sign in",

    onboarding_auth_title: "Let's get you set up",
    onboarding_auth_subtitle: "Choose how you’d like to continue. It only takes a moment.",
    onboarding_auth_apple: "Continue with Apple",
    onboarding_auth_google: "Continue with Google",
    onboarding_auth_facebook: "Continue with Facebook",
    onboarding_auth_email: "Continue with Email",
    onboarding_auth_sso: "Continue with SSO",
    onboarding_auth_footer: "Already have an account?",
    onboarding_auth_login: "Log in",
    onboarding_auth_safe: "Your info is safe with me. 💛",

    login_title: "Login",
    login_email_placeholder: "Email",
    login_password_placeholder: "Password",
    login_cta: "Sign In",
    login_forgot_password: "Forgot password?",
    login_privacy_terms: "By continuing, you agree to Bloom’s Terms of Service and Privacy Policy.",

    signup_title: "Create my account",
    signup_password_placeholder: "Password",
    signup_confirm_password_placeholder: "Confirm password",
    signup_cta: "Register",
    signup_consent_error: "You must accept the terms to continue.",

    survey_step1_title: "Let’s find your Bloom",
    survey_step2_title: "What habit type do you want to start with?",
    survey_step3_title: "How often do you want to check in on this habit?",
    survey_step1_sub: "A few quick questions so I can guide you the right way.",
    survey_step2_sub: "You can always add the other later.",
    survey_step3_sub: "Pick whatever feels doable, small and steady beats big and short-lived.",
    survey_step1_quote: "Whatever brought you here is a good enough reason.",
    survey_step2_quote: "A fresh start is waiting for you!",
    survey_step3_quote: "Small steps lead to big blooms!",
    survey_option_build_habits: "To build better daily habits",
    survey_option_break_habit: "To break free from a habit",
    survey_option_control: "To feel more in control",
    survey_option_explore: "Just exploring Bloom",
    survey_option_build_mode: "Build a good habit (Green mode)",
    survey_option_quit_mode: "Quit a bad habit (Purple mode)",
    survey_option_both: "A bit of both",
    survey_option_daily: "Daily",
    survey_option_often: "A few times a week",
    survey_option_weekly: "Weekly",
    survey_option_unsure: "I’m not sure yet",

    success_title: "You’re all set!",
    success_subtext: "I’ve got your first dashboard ready. Let’s take the first step, together.",
    success_cta: "Enter Bloom →",

    onboarding_intro_title: "Hello!",
    onboarding_intro_subtitle1: "My name is Sunny bloom.",
    onboarding_intro_subtitle2: "A gentle experience to track your habits, celebrate progress, and move at your own pace.",
    onboarding_intro_cta: "I start gently",
    onboarding_welcome_title: "hello, my name is sunny bloom.",
    onboarding_welcome_subtitle: "A gentle experience to track your habits, celebrate progress, and move at your own pace without pressure.",
    onboarding_mode_title: "let's get to know you a little",
    onboarding_mode_subtitle: "a few quick questions to suggest the best mode from the start.",
    onboarding_mode_question1: "You mainly want to...",
    onboarding_mode_question2: "The easiest rhythm for you is...",
    onboarding_mode_suggestion: "Our suggestion",
    onboarding_continue: "continue",
    onboarding_create_title: "create your first habit",
    onboarding_create_cta: "create and start",
    onboarding_back: "back",
    onboarding_mode_build: "Build",
    onboarding_mode_quit: "Quit",
    onboarding_mode_guided: "Guided",
    onboarding_mode_both: "Both",
    onboarding_mode_build_desc: "new habits",
    onboarding_mode_quit_desc: "bad habits",
    onboarding_mode_guided_desc: "a gentle start",
    onboarding_mode_both_desc: "depending on the day",
    onboarding_focus_small: "Small step",
    onboarding_focus_daily: "Every day",
    onboarding_focus_weekly: "Per week",
    onboarding_focus_small_desc: "1 action at a time",
    onboarding_focus_daily_desc: "a regular routine",
    onboarding_focus_weekly_desc: "broader goals",
    onboarding_suggest_guided: "Guided mode",
    onboarding_suggest_quit: "Quit mode",
    onboarding_suggest_build: "Build mode",
    onboarding_suggest_small: "We start light with one single priority.",
    onboarding_suggest_daily: "We set a simple routine to repeat daily.",
    onboarding_suggest_weekly: "We keep broader goals to track weekly.",

    // Calendar sync
    calendar_sync_title: "calendar sync",
    calendar_sync_connected: "connected",
    calendar_sync_disconnected: "not connected",
    calendar_sync_connecting: "connecting...",
    calendar_sync_connect_google: "connect with Google",
    calendar_sync_auto_label: "automatic sync",
    calendar_sync_auto_desc: "adds your habits to Google Calendar",
    calendar_sync_last: "last sync",
    calendar_sync_now: "sync now",
    calendar_sync_disconnect: "disconnect",

    // About
    about_title: "About Bloom",
    about_mission_title: "Our Mission",
    about_mission_text: "At Bloom, our mission is to help you grow healthy habits and thrive day after day. We believe small consistent steps lead to meaningful transformation.",
    about_version_title: "App Version",

    // Journal mood labels
    mood_radiant: "radiant",
    mood_good: "good",
    mood_neutral: "neutral",
    mood_hard: "hard",
    mood_tough: "tough",
  },

  es: {
    // Navigation
    nav_dashboard: "inicio",
    nav_profile: "perfil",
    nav_menu: "menú",
    nav_subscription: "suscripción",
    nav_journal: "diario",
    nav_widgets: "widgets",

    // Dashboard
    petals: "pétalos",
    build_mode: "modo construcción",
    quit_mode: "modo abandono",
    build_tagline: "construye",
    quit_tagline: "libérate",
    streak_days: "días de racha",
    freed_days: "días libres",
    hi_user: "Hola, {{name}}",
    dashboard_tagline: "¡Hagamos hábitos juntos!",
    dashboard_quote: "Gran viaje. ¡Tu esfuerzo es legendario!",
    dashboard_suggested: "Sugerido para ti",
    dashboard_created_title: "Hábitos",
    dashboard_created_label: "creados",
    dashboard_build_count_title: "Construcción",
    dashboard_build_count_label: "hábitos",
    dashboard_recent_title: "Hábitos recientes",
    daily_goals_title: "¡Tus metas diarias casi están listas! 🔥",
    daily_goals_subtitle: "{{completed}} de {{total}} completados",
    habits_title: "Hábitos",
    view_all: "Ver todo",
    show_less: "Ver menos",
    habit_done: "¡Hecho por hoy!",
    habit_not_started: "Aún no ha comenzado",
    no_habits_yet: "Aún no hay hábitos. ¡Empieza pequeño!",
    create_habit_cta: "+ Crear un hábito",
    done_today: "✓ hecho hoy",
    freed_day: "✓ día libre",
    add_habit: "+ añadir hábito",
    no_build_habits: "sin hábitos en construcción",
    no_quit_habits: "sin hábitos que abandonar por ahora",
    swipe_build: "← desliza para ver modo construcción →",
    swipe_quit: "← desliza para ver modo abandono",

    // Profile
    profile_title: "perfil & historial",
    your_journey: "tu viaje bloom",
    member_since: "miembro desde mayo 2026",
    active_habits: "hábitos activos",
    total_days: "días totales",
    petals_count: "pétalos",
    year_activity: "actividad del año",
    less: "menos",
    more: "más",
    insights: "estadísticas",
    longest_streak: "racha más larga",
    best_day: "mejor día",
    best_habit: "hábito más exitoso",
    data_note: "💜 todos tus datos se guardan con cuidado. incluso los días perdidos son visibles para ayudarte a entender tu camino.",
    days_label: ["l", "m", "m", "j", "v", "s", "d"],
    months_label: ["ene", "feb", "mar", "abr", "may", "jun", "jul", "ago", "sep", "oct", "nov", "dic"],

    // Settings
    settings_title: "ajustes",
    appearance: "appariencia",
    appearance_desc: "temas, sonidos y animaciones",
    theme_system: "sistema",
    custom_colors: "colores personalizados",
    primary_color: "color principal",
    background_color: "fondo",
    text_color: "texto",
    dark_mode: "modo oscuro",
    dark_mode_on: "noche profunda activado",
    dark_mode_off: "crema sunbeam activado",
    forest: "bosque",
    ocean: "océano",
    sound_effects: "efectos de sonido",
    sound_effects_on_label: "activados",
    sound_effects_off_label: "desactivados",
    animations: "animaciones",
    animations_on_label: "activadas",
    animations_off_label: "desactivadas",
    notifications: "notificaciones",
    notif_examples: "ejemplos de recordatorios amables:",
    integrations: "integraciones",
    gcal: "Google Calendar",
    gcal_desc: "sincroniza tus hábitos con tu calendario",
    account: "cuenta",
    manage_sub: "gestionar suscripción",
    manage_sub_desc: "versión seedling (gratuita)",
    export_data: "exportar mis datos",
    export_data_desc: "descarga tu historial",
    about: "sobre bloom",
    version: "versión 1.0.0",
    support: "soporte",
    help_center: "centro de ayuda",
    contact_us: "contáctanos",
    privacy: "política de privacidad",
    language: "idioma",
    footer: "hecho con 💛 por el equipo bloom",
    bloom_premium: "bloom premium",
    premium_desc: "hábitos ilimitados • 7 emociones de sunny • sin anuncios",
    discover: "descubrir bloom",

    // Journal
    journal_title: "diario personal",
    journal_subtitle: "tus pensamientos, tu espacio",
    new_entry: "nueva entrada",
    today: "hoy",
    how_feeling: "¿cómo te sientes hoy?",
    write_placeholder: "escribe aquí... sin presión, sin juicios.",
    save_entry: "guardar",
    entries: "entradas",
    no_entries: "aún no hay entradas. empieza a escribir 🌱",

    // Widgets
    widgets_title: "widgets",
    widgets_subtitle: "personaliza tu experiencia",
    streak_widget: "widget racha",
    streak_widget_desc: "muestra tu racha diaria",
    heatmap_widget: "widget heatmap",
    heatmap_widget_desc: "resumen de actividad",
    sunny_widget: "widget sunny",
    sunny_widget_desc: "sunny en tu pantalla de inicio",
    add_widget: "añadir",
    added: "añadido ✓",
    coming_soon: "próximamente",
    tutorial_step1: "Hola, soy Sunny. En 30 segundos te enseño lo esencial.",
    tutorial_step2: "Aquí ves tus pétalos. Cada check-in los hace crecer.",
    tutorial_step3: "En esta zona están tus hábitos de hoy.",
    tutorial_step4: "Con este selector cambias rápido entre construir y abandonar.",
    tutorial_step5: "Esta barra abre perfil, diario, widgets y más.",
    tutorial_step6: "Perfecto. Empieza pequeño hoy y sigue constante mañana.",

    // Common
    back: "volver",
    save: "guardar",
    cancel: "cancelar",
    close: "cerrar",

    // Onboarding
    onboarding_brand_step: "primer paso",
    onboarding_consent_title: "Tu privacidad, nuestra prioridad.",
    onboarding_consent_subtitle: "Para ofrecerte la mejor experiencia Bloom, necesitamos recopilar algunos datos anónimos.",
    onboarding_consent_cta: "Acepto y continúo",
    onboarding_consent_footer: "Al continuar, aceptas las Condiciones de servicio y la Política de privacidad de Bloom.",

    onboarding_welcome_hi_sunny: "¡Hola, soy Sunny! 🌻",
    onboarding_welcome_subtext: "Estoy muy feliz de que estés aquí. Cultivemos algo bueno juntos, un pequeño hábito a la vez.",
    onboarding_welcome_cta: "¡Vamos! →",
    onboarding_welcome_already_account: "¿Ya tienes una cuenta?",
    onboarding_welcome_signin: "Iniciar sesión",

    onboarding_auth_title: "Preparemos tu llegada",
    onboarding_auth_subtitle: "Elige cómo deseas continuar. Solo toma un momento.",
    onboarding_auth_apple: "Continuar con Apple",
    onboarding_auth_google: "Continuar con Google",
    onboarding_auth_facebook: "Continuar con Facebook",
    onboarding_auth_email: "Continuar con Email",
    onboarding_auth_sso: "Continuar con SSO",
    onboarding_auth_footer: "¿Ya tienes una cuenta?",
    onboarding_auth_login: "Iniciar sesión",
    onboarding_auth_safe: "Tu información está segura conmigo. 💛",

    login_title: "Conexión",
    login_email_placeholder: "Correo electrónico",
    login_password_placeholder: "Contraseña",
    login_cta: "Iniciar sesión",
    login_forgot_password: "¿Has olvidado tu contraseña?",
    login_privacy_terms: "Al continuar, aceptas las Condiciones de servicio y la Política de privacidad de Bloom.",

    survey_step1_title: "Encontremos tu Bloom",
    survey_step2_title: "¿Con qué tipo de hábito quieres empezar?",
    survey_step3_title: "¿Con qué frecuencia quieres seguir este hábito?",
    survey_step1_sub: "Unas preguntas rápidas para que pueda guiarte lo mejor posible.",
    survey_step2_sub: "Siempre podrás añadir el otro más tarde.",
    survey_step3_sub: "Elige lo que te parezca factible, la constancia supera a la intensidad.",
    survey_step1_quote: "No importa lo que te traiga aquí, es una excelente razón.",
    survey_step2_quote: "¡Un nuevo comienzo te espera!",
    survey_step3_quote: "¡Los pequeños pasos llevan a grandes floraciones!",
    survey_option_build_habits: "Crear mejores hábitos",
    survey_option_break_habit: "Liberarse de un hábito",
    survey_option_control: "Sentirme más en control",
    survey_option_explore: "Solo explorar Bloom",
    survey_option_build_mode: "Crear un buen hábito (Modo Verde)",
    survey_option_quit_mode: "Dejar un mal hábito (Modo Morado)",
    survey_option_both: "Un poco de ambos",
    survey_option_daily: "Diario",
    survey_option_often: "Unas veces por semana",
    survey_option_weekly: "Semanal",
    survey_option_unsure: "Aún no lo sé",

    success_title: "¡Todo listo!",
    success_subtext: "Tu primer panel de control está listo. Demos el primer paso juntos.",
    success_cta: "Entrar en Bloom →",

    onboarding_intro_title: "¡Hola!",
    onboarding_intro_subtitle1: "Me llamo Sunny bloom.",
    onboarding_intro_subtitle2: "Una experiencia suave para seguir tus hábitos, celebrar avances y avanzar a tu ritmo.",
    onboarding_intro_cta: "Empiezo suave",
    onboarding_welcome_title: "hola, me llamo sunny bloom.",
    onboarding_welcome_subtitle: "Una experiencia suave para seguir tus hábitos, celebrar avances y avanzar a tu ritmo sin presión.",
    onboarding_mode_title: "vamos a conocerte un poco",
    onboarding_mode_subtitle: "unas preguntas rápidas para sugerirte el mejor modo desde el inicio.",
    onboarding_mode_question1: "Sobre todo quieres...",
    onboarding_mode_question2: "Lo más fácil para ti es...",
    onboarding_mode_suggestion: "Nuestra sugerencia",
    onboarding_continue: "continuar",
    onboarding_create_title: "crea tu primer hábito",
    onboarding_create_cta: "crear y empezar",
    onboarding_back: "volver",
    onboarding_mode_build: "Construir",
    onboarding_mode_quit: "Dejar",
    onboarding_mode_guided: "Guiado",
    onboarding_mode_both: "Ambos",
    onboarding_mode_build_desc: "nuevos hábitos",
    onboarding_mode_quit_desc: "malos hábitos",
    onboarding_mode_guided_desc: "inicio suave",
    onboarding_mode_both_desc: "según el día",
    onboarding_focus_small: "Paso pequeño",
    onboarding_focus_daily: "Cada día",
    onboarding_focus_weekly: "Por semana",
    onboarding_focus_small_desc: "1 acción a la vez",
    onboarding_focus_daily_desc: "rutina regular",
    onboarding_focus_weekly_desc: "objetivos más amplios",
    onboarding_suggest_guided: "Modo guiado",
    onboarding_suggest_quit: "Modo dejar",
    onboarding_suggest_build: "Modo construir",
    onboarding_suggest_small: "Empezamos ligero con una sola prioridad.",
    onboarding_suggest_daily: "Planteamos una rutina simple para repetir cada día.",
    onboarding_suggest_weekly: "Mantenemos objetivos más amplios para seguir cada semana.",

    // Calendar sync
    calendar_sync_title: "sincronización de calendario",
    calendar_sync_connected: "conectado",
    calendar_sync_disconnected: "no conectado",
    calendar_sync_connecting: "conectando...",
    calendar_sync_connect_google: "conectar con Google",
    calendar_sync_auto_label: "sincronización automática",
    calendar_sync_auto_desc: "añade tus hábitos a Google Calendar",
    calendar_sync_last: "dernière sincronización",
    calendar_sync_now: "sincronizar ahora",
    calendar_sync_disconnect: "desconectar",

    // About
    about_title: "Acerca de Bloom",
    about_mission_title: "Nuestra misión",
    about_mission_text: "En Bloom, nuestra misión es ayudarte a cultivar hábitos saludables y crecer día tras día. Creemos que los pequeños pasos constantes generan grandes cambios.",
    about_version_title: "Versión de la aplicación",

    // Journal mood labels
    mood_radiant: "radiante",
    mood_good: "bien",
    mood_neutral: "neutral",
    mood_hard: "difícil",
    mood_tough: "duro",

    signup_title: "Crear mi cuenta",
    signup_password_placeholder: "Contraseña",
    signup_confirm_password_placeholder: "Confirmar contraseña",
    signup_cta: "Registrarse",
    signup_consent_error: "Debes aceptar los términos para continuar.",
  },
} as const;

type TranslationKeys = keyof typeof translations.fr;

interface LanguageContextType {
  lang: Language;
  setLang: (l: Language) => void;
  // AJOUT DE READONLY ICI POUR FIXER LA SIGNATURE DE L'INTERFACE
  t: (key: TranslationKeys) => string | readonly string[];
}

const LanguageContext = createContext<LanguageContextType | null>(null);

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [lang, setLangState] = useState<Language>(() => {
    if (typeof window !== "undefined") {
      return (localStorage.getItem("bloom_lang") as Language) || "fr";
    }
    return "fr";
  });

  const setLang = (l: Language) => {
    localStorage.setItem("bloom_lang", l);
    setLangState(l);
  };

  const t = (key: TranslationKeys): string | readonly string[] => {
    return (translations[lang] as Record<string, string | readonly string[]>)[key] ?? key;
  };

  return (
    <LanguageContext.Provider value={{ lang, setLang, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const ctx = useContext(LanguageContext);
  if (!ctx) throw new Error("useLanguage must be used inside LanguageProvider");
  return ctx;
}