"use client";

import { createContext, useContext, useState, ReactNode } from "react";

export type Language = "fr" | "en" | "es";

export const translations = {
  fr: {
    // Navigation
    nav_dashboard: "accueil",
    nav_profile: "profil",
    nav_menu: "menu",
    nav_subscription: "abonnement",
    nav_journal: "journal",
    nav_widgets: "widgets",

    // Dashboard
    petals: "pétales",
    build_mode: "mode encrage",
    quit_mode: "mode sevrage",
    build_tagline: "construis",
    quit_tagline: "libère-toi",
    streak_days: "jours de série",
    freed_days: "jours libérés",
    hi_user: "Salut, {{name}}",
    dashboard_tagline: "Cultivons tes habitudes ensemble !",
    dashboard_tagline_quit: "Prêt à te libérer ?",
    dashboard_tagline_control: "Reprends les rênes !",
    dashboard_tagline_build: "Construisons demain !",
    dashboard_quote: "Très beau parcours. Ton effort est légendaire !",
    dashboard_suggested: "Suggéré pour toi",
    dashboard_created_title: "Habitudes",
    dashboard_created_label: "créées",
    dashboard_build_count_title: "Encrage",
    dashboard_build_count_label: "habitudes",
    dashboard_recent_title: "Habitudes récentes",
    daily_goals_title: "Tes objectifs du jour sont presque atteints ! 🔥",
    daily_goals_subtitle: "{{completed}} sur {{total}} complétés",
    habits_title: "Habitudes",
    view_all: "Voir tout",
    show_less: "Réduire",
    habit_done: "Fait pour aujourd'hui !",
    habit_not_started: "Pas encore commencé",
    no_habits_yet: "Pas encore d'habitudes. Commence petit !",
    create_habit_cta: "+ Créer une habitude",
    done_today: "✓ fait aujourd'hui",
    freed_day: "✓ jour réussi",
    add_habit: "+ ajouter une habitude",
    add_habit_button: "Ajouter une habitude",
    no_habits: "Aucune habitude",
    partner_space: "Espace Partenaire",
    upgrade_forever_desc: "Passe à Bloom Forever pour supprimer les publicités 🌻",
    shield_activated: "Bouclier activé pour 24h !",
    limit_reached: "Limite atteinte",
    seedling_limit_desc: "Le forfait gratuit est limité à 3 habitudes simultanées.",

    // Habit Calendar
    habit_calendar_title: "Suivi des habitudes",
    habits_of: "Habitudes du",
    no_habits_scheduled: "Aucune habitude prévue ce jour.",
    build_mode_label: "Encrage",
    quit_mode_label: "Sevrage",
    completed: "complété",

    // Habit Create/Edit
    habit_create_title: "Nouvelle habitude",
    habit_edit_title: "Modifier l'habitude",
    habit_type: "Type",
    habit_what: "Quoi ?",
    habit_quit_what: "Arrêter quoi ?",
    habit_name_placeholder: "Méditer, Courir...",
    habit_quit_placeholder: "Sucre, Tabac...",
    habit_frequency_time: "Fréquence & Temps",
    seedling_fixed: "Seedling (Fixe)",
    frequency_daily: "Quotidien",
    frequency_weekly: "Hebdo",
    frequency_custom: "Perso",
    choose_days: "Choisir les jours",
    reps_per_day: "Répétition / jour",
    duration_min: "Durée (min)",
    reminder: "Rappel",
    end_habit_question: "Fin de l'habitude ?",
    by_date: "Par date",
    by_count: "Par nombre de fois",
    total_executions: "exécutions totales",
    reminder_message: "Message de rappel",
    reminder_message_placeholder: "Ex: 'N'oublie pas de boire de l'eau !'",
    update_habit: "Mettre à jour",
    save_habit: "Enregistrer l'habitude",
    premium_feature: "Fonctionnalité Premium",
    custom_cadence_locked_desc: "Les cadences personnalisées sont réservées aux abonnés Bloom.",

    // Habit Detail
    current_level: "niveau actuel",
    timer: "minuteur",
    tip_of_the_day: "conseil du jour",
    history: "historique",
    stats: "statistiques",
    see_calendar: "voir le calendrier",
    see_progress: "vois ta progression",
    no_habit_selected: "aucune habitude sélectionnée",
    encourage_strong: "Tu tiens un rythme fort: {{streak}} jours, {{effort}}.",
    encourage_steady: "Belle constance. Continue ce {{effort}} aujourd'hui.",
    encourage_start: "Mini action maintenant = progression réelle. Continue avec un {{effort}}.",
    tips_build: [
      "commence petit : 2 minutes valent mieux que 0 minute",
      "fais-le à la même heure chaque jour pour créer une routine",
      "prépare ton environnement la veille pour éliminer les frictions",
      "relie cette habitude à une habitude existante (ex: après le café)",
      "célèbre chaque victoire, même minuscule 🌻",
    ],
    tips_quit: [
      "identifie le déclencheur qui précède l'habitude à quitter",
      "remplace l'habitude par quelque chose de positif",
      "évite les environnements qui déclenchent l'envie",
      "rappelle-toi pourquoi tu veux arrêter (écris-le)",
      "chaque jour sans rechute est une victoire 💎",
    ],

    // Journal
    journal_title: "journal intime",
    journal_subtitle: "tes pensées, ton espace",
    new_entry: "nouvelle entrée",
    today: "aujourd'hui",
    how_feeling: "comment tu te sens aujourd'hui ?",
    write_placeholder: "écris ici... sans pression, sans jugement.",
    save_entry: "enregistrer",
    entries: "entrées",
    no_entries: "pas encore d'entrées. commence à écrire 🌱",
    edit_note: "Modifier ma note",
    write_first_thought: "Écrire ma première pensée",
    update_note: "Mettre à jour",

    // Profile
    profile_title: "profil & historique",
    your_journey: "ton parcours bloom",
    member_since: "membre depuis mai 2026",
    active_habits: "habitudes actives",
    total_days: "jours totaux",
    petals_count: "pétales",
    year_activity: "activité de l'année",
    less: "moins",
    more: "plus",
    insights: "insights",
    insights_desc: "Tes tendances et records",
    longest_streak: "plus longue série",
    best_day: "meilleur jour",
    best_habit: "habitude la plus réussie",
    data_note: "💜 toutes tes données sont conservées avec bienveillance. même les jours manqués restent visibles pour t'aider à comprendre ton parcours.",
    days_label: ["l", "m", "m", "j", "v", "s", "d"],
    months_label: ["jan", "fév", "mar", "avr", "mai", "jun", "jul", "aoû", "sep", "oct", "nov", "déc"],
    settings_button: "réglages",
    pass_pro: "Passer Pro",
    logout: "Se déconnecter",
    heatmap_locked_title: "Heatmap complète",
    heatmap_locked_desc: "Passe à Bloom pour visualiser ton activité sur toute l'année.",
    unlock: "Débloquer",
    unlock_insights: "Débloquer les Insights",

    // Settings Menu
    settings_menu_title: "Paramètres",
    menu_settings_title: "Les réglages",
    menu_settings_sub: "Thèmes, sons et notifications",
    menu_journal_title: "Le journal",
    menu_journal_sub: "Tes pensées, ton espace",
    menu_profile_title: "Le profil & historique",
    menu_profile_sub: "Tes statistiques et ton parcours",

    // Notifications
    notifications_title: "Notifications",
    notif_well_done: "Bien joué !",
    notif_its_time: "C'est l'heure !",
    notif_body_done: "Tu as complété ton objectif \"{{name}}\" pour aujourd'hui.",
    notif_body_todo: "N'oublie pas de valider \"{{name}}\" pour garder ta série de {{streak}} jours.",
    at_time: "à",
    no_notifications: "Aucune notification pour le moment.",
    notif_build_title: "C'est l'heure d'ancrer ! 🌻",
    notif_quit_title: "Reste fort(e) ! 🕊️",
    notif_body_prefix: "C'est le moment pour : ",

    // Habit Validation Action
    error_oops: "Oups !",
    error_habit_not_found: "Cette habitude n'existe plus ou a été supprimée.",
    back_to_dashboard: "Retour au tableau de bord",
    its_time: "C'est l'heure !",
    did_you_realize: "Est-ce que tu as réalisé ton habitude",
    ignore: "Ignorer",
    validate: "Valider",
    habit_validated_success: "Super ! {{name}} validé.",

    // Auth & Generic Errors
    error_all_fields_required: "Veuillez remplir tous les champs.",
    error_passwords_mismatch: "Les mots de passe ne correspondent pas.",
    full_name_placeholder: "Nom complet",

    // Calendar Sync
    features_title: "fonctionnalités",
    feature_1_title: "événements automatiques",
    feature_1_desc: "tes habitudes quotidiennes sont ajoutées à ton calendrier",
    feature_2_title: "rappels synchronisés",
    feature_2_desc: "reçois des notifications au bon moment",
    feature_3_title: "check-in rapide",
    feature_3_desc: "marque tes habitudes terminées directement depuis Google Calendar",
    feature_4_title: "vue d'ensemble",
    feature_4_desc: "visualise toutes tes habitudes en un coup d'œil",
    privacy_title: "tes données restent privées",
    privacy_desc: "bloom accède uniquement à ton calendrier pour ajouter et mettre à jour tes événements d'habitudes. nous ne lisons jamais tes autres événements personnels.",

    // Check-in Modal
    daily_validation: "validation quotidienne",
    bravo_for: "bravo pour",
    how_feeling_today: "comment te sens-tu aujourd'hui ?",
    personal_note_optional: "note personnelle (optionnel)",
    note_placeholder: "qu'as-tu ressenti ? qu'as-tu appris ?",
    validate_day: "valider la journée",
    mood_excellent: "excellent",
    mood_good_label: "bien",
    mood_neutral_label: "neutre",
    mood_hard_label: "difficile",
    mood_struggling_label: "très dur",

    // Milestone Modal
    milestone_reached: "🎉 jalon atteint !",
    milestone_7_msg: "Sunny devient de plus en plus fort(e) !",
    milestone_30_msg: "Sunny est en PLEINE floraison. Tu l'as fait !",
    milestone_100_msg: "Sunny est légendaire maintenant. Incroyable.",
    milestone_default_msg: "Incroyable ! Continue comme ça.",
    dance_with_sunny: "danser avec sunny !",
    share_success: "partager mon succès",
    share_text: "{{streak}} jours de série sur Bloom ! 🌻",

    // Widgets
    how_to_install: "Comment installer ?",
    install_instructions: "Maintenez votre doigt sur une zone vide de votre écran d'accueil, appuyez sur le bouton **(+)** ou **\"Widgets\"** et recherchez **Bloom**.",

    // Shield Modal
    bloom_shield_activated: "bloom shield activé",
    streak_protected: "série protégée",
    shield_modal_desc: "un pétale de cristal a sauvé la mise. série protégée. va te reposer — sunny gère la situation.",
    used_crystal_petal: "tu as utilisé 1 pétale de cristal",
    thanks_sunny: "merci sunny 💜",

    // Paywall
    paywall_title: "Forfaits Bloom",
    upgrade_title: "Passe à la vitesse supérieure",
    upgrade_subtitle: "Libère Sunny et débloque toutes tes capacités",
    plan_seedling: "SEEDLING",
    plan_bloom: "BLOOM (Premium)",
    plan_forever: "BLOOM FOREVER",
    period_free: "gratuit",
    period_monthly: "/ mois (ou 34.99$/an)",
    period_once: "paiement unique",
    recommended: "Conseillé",
    current_plan_label: "Actuel",
    version_current: "Version actuelle",
    pass_to_bloom: "Passer à Bloom",
    become_founder: "Devenir Fondateur",
    feature_limit_3: "Limité à 3 habitudes simultanées",
    feature_basic_states: "États basiques (Neutral, Growing, Blooming)",
    feature_sunny_classic: "Widget d'écran d'accueil (Sunny Classic)",
    feature_basic_stats: "Statistiques élémentaires",
    feature_fixed_cadence: "Cadence fixe (Quotidienne)",
    feature_ads_present: "Bannières publicitaires présentes",
    feature_unlimited_habits: "Nombre d'habitudes illimité",
    feature_7_states: "Les 7 états émotionnels inclus",
    feature_all_widgets: "Widgets Accueil + Verrouillage",
    feature_full_heatmap: "Heatmap complète & historique",
    feature_custom_cadence: "Cadence personnalisée (Hebdo, etc.)",
    feature_no_ads: "Aucune publicité",
    feature_3_crystals: "+3 Cristaux offerts / mois",
    feature_all_bloom: "Tout le forfait BLOOM",
    feature_multiplier: "Multiplicateur Pétales x1.5",
    feature_skin_legend: "Skin exclusive \"Legend\"",
    feature_founder_badge: "Badge Fondateur",
    feature_lifetime: "Accès à vie illimité",

    // Settings
    settings_title: "paramètres",
    appearance: "apparence",
    appearance_desc: "thèmes, sons et animations",
    theme_system: "système",
    custom_colors: "couleurs personnalisées",
    primary_color: "couleur principale",
    background_color: "arrière-plan",
    text_color: "texte",
    dark_mode: "mode sombre",
    dark_mode_on: "deep night activé",
    dark_mode_off: "sunbeam cream activé",
    forest: "forêt",
    ocean: "océan",
    sound_effects: "effets sonores",
    sound_effects_on_label: "activés",
    sound_effects_off_label: "désactivés",
    animations: "animations",
    animations_on_label: "activées",
    animations_off_label: "désactivées",
    notifications: "notifications",
    notif_examples: "exemples de rappels bienveillants :",
    notif_example_1: "good morning. sunny's up and waiting — don't leave them on read.",
    notif_example_2: "hey, juste un petit rappel doux. sunny croit en toi 🌻",
    notif_example_3: "tu as construit une belle série. viens valider ta journée ?",
    notif_toggle_desc: "active ou coupe les rappels bienveillants",
    integrations: "intégrations",
    gcal: "Google Calendar",
    gcal_desc: "synchronise tes habitudes avec ton calendrier",
    account: "compte",
    account_integrations: "compte & intégrations",
    account_integrations_desc: "abonnement, export et connexion calendrier",
    manage_sub: "gérer l'abonnement",
    manage_sub_desc: "version seedling (gratuite)",
    export_data: "exporter mes données",
    export_data_desc: "télécharge ton historique",
    about: "À propos de bloom",
    version: "version 1.0.0",
    support: "support",
    support_desc: "aide, contact et confidentialité",
    help_center: "centre d'aide",
    contact_us: "nous contacter",
    privacy: "politique de confidentialité",
    language: "langue",
    language_desc: "change la langue sans quitter la page",
    footer: "fait avec 💛 par l'équipe bloom",
    bloom_premium: "bloom premium",
    premium_desc: "habitudes illimitées • 7 émotions de sunny • zéro pub",
    discover: "découvrir bloom",

    // Common
    back: "retour",
    save: "enregistrer",
    cancel: "annuler",
    close: "fermer",

    // Onboarding
    onboarding_brand_step: "premier pas",
    onboarding_consent_title: "Ta vie privée, notre priorité.",
    onboarding_consent_subtitle: "Pour t'offrir la meilleure expérience Bloom, nous avons besoin de collecter quelques données de manière anonyme.",
    onboarding_consent_cta: "J'accepte et je continue",
    onboarding_consent_footer: "En continuant, tu acceptes nos Conditions d'utilisation et notre Politique de confidentialité.",

    onboarding_welcome_hi_sunny: "Salut, je suis Sunny ! 🌻",
    onboarding_welcome_subtext: "Je suis si heureux que tu sois là. Cultivons quelque chose de bien ensemble, une petite habitude à la fois.",
    onboarding_welcome_cta: "C'est parti ! →",
    onboarding_welcome_already_account: "J'ai déjà un compte ?",
    onboarding_welcome_signin: "Se connecter",

    onboarding_auth_title: "Préparons ton arrivée",
    onboarding_auth_subtitle: "Choisis comment tu souhaites continuer. Cela ne prend qu'un instant.",
    onboarding_auth_apple: "Continuer avec Apple",
    onboarding_auth_google: "Continuer avec Google",
    onboarding_auth_facebook: "Continuer avec Facebook",
    onboarding_auth_email: "Continuer avec Email",
    onboarding_auth_sso: "Continuer avec SSO",
    onboarding_auth_footer: "Tu as déjà un compte ?",
    onboarding_auth_login: "Se connecter",
    onboarding_auth_safe: "Tes infos sont en sécurité avec moi. 💛",

    login_title: "Connexion",
    login_email_placeholder: "Email",
    login_password_placeholder: "Mot de passe",
    login_cta: "Se connecter",
    login_forgot_password: "Mot de passe oublié ?",
    login_privacy_terms: "En continuant, tu acceptes les Conditions d'utilisation et la Politique de confidentialité de Bloom.",

    signup_title: "Je crée mon compte",
    signup_password_placeholder: "Mot de passe",
    signup_confirm_password_placeholder: "Confirmer le mot de passe",
    signup_cta: "Enregistrer",
    signup_consent_error: "Tu dois accepter les conditions pour continuer.",

    survey_step1_title: "Trouvons ton Bloom",
    survey_step2_title: "Par quel type d'habitude veux-tu commencer ?",
    survey_step3_title: "À quelle fréquence veux-tu suivre cette habitude ?",
    survey_step1_sub: "Quelques questions rapides pour que je puisse te guider au mieux.",
    survey_step2_sub: "Tu pourras toujours ajouter l'autre plus tard.",
    survey_step3_sub: "Choisis ce qui te semble réalisable, la régularité bat la précocité.",
    survey_step1_quote: "Peu importe ce qui t'amène ici, c'est une excellente raison.",
    survey_step2_quote: "Un nouveau départ t'attend !",
    survey_step3_quote: "Les petits pas mènent à de grandes floraisons !",
    survey_option_build_habits: "Créer de meilleures habitudes",
    survey_option_break_habit: "Se libérer d'une habitude",
    survey_option_control: "Me sentir plus en contrôle",
    survey_option_explore: "Juste explorer Bloom",
    survey_option_build_mode: "Créer une bonne habitude (Mode Vert)",
    survey_option_quit_mode: "Arrêter une mauvaise habitude (Mode Mauve)",
    survey_option_both: "Un peu des deux",
    survey_option_daily: "Quotidien",
    survey_option_often: "Quelques fois par semaine",
    survey_option_weekly: "Hebdomadaire",
    survey_option_unsure: "Je ne sais pas encore",

    success_title: "Tu es prêt !",
    success_subtext: "Ton premier tableau de bord est prêt. Faisons le premier pas, ensemble.",
    success_cta: "Entrer dans Bloom →",

    onboarding_intro_title: "Hello!",
    onboarding_intro_subtitle1: "Je m'appelle Sunny bloom.",
    onboarding_intro_subtitle2: "Une expérience douce pour suivre tes habitudes, te célébrer et avancer à ton rythme.",
    onboarding_intro_cta: "Je commence doucement",
    onboarding_welcome_title: "hello, je m'appelle sunny bloom.",
    onboarding_welcome_subtitle: "Une expérience douce pour suivre tes habitudes, te célébrer et avancer à ton rythme, sans pression.",
    onboarding_mode_title: "on te connaît un peu mieux",
    onboarding_mode_subtitle: "quelques questions rapides pour te proposer le bon mode dès le début.",
    onboarding_mode_question1: "Tu veux surtout...",
    onboarding_mode_question2: "Le plus simple pour toi, c'est...",
    onboarding_mode_suggestion: "Notre suggestion",
    onboarding_continue: "continuer",
    onboarding_create_title: "crée ta première habitude",
    onboarding_create_cta: "créer et commencer",
    onboarding_back: "retour",
    onboarding_mode_build: "Construire",
    onboarding_mode_quit: "Sevrer",
    onboarding_mode_guided: "Assisté",
    onboarding_mode_both: "Les deux",
    onboarding_mode_build_desc: "de nouvelles habitudes",
    onboarding_mode_quit_desc: "des mauvaises habitudes",
    onboarding_mode_guided_desc: "un départ doux",
    onboarding_mode_both_desc: "selon les jours",
    onboarding_focus_small: "Petit pas",
    onboarding_focus_daily: "Tous les jours",
    onboarding_focus_weekly: "Par semaine",
    onboarding_focus_small_desc: "1 action à la fois",
    onboarding_focus_daily_desc: "une routine régulière",
    onboarding_focus_weekly_desc: "des objectifs plus larges",
    onboarding_suggest_guided: "Mode assisté",
    onboarding_suggest_quit: "Mode sevrage",
    onboarding_suggest_build: "Mode encrage",
    onboarding_suggest_small: "On commence léger, avec une seule priorité.",
    onboarding_suggest_daily: "On pose une routine simple à reproduire chaque jour.",
    onboarding_suggest_weekly: "On garde des objectifs plus larges, à suivre chaque semaine.",

    // Onboarding Habit Specific
    habit_name_label: "nom de l'habitude",
    habit_quit_label: "habitude à quitter",
    habit_name_ex: "ex: méditer 10 minutes",
    habit_quit_ex: "ex: fumer",
    cadence: "cadence",
    daily: "quotidienne",
    every_day: "tous les jours",
    custom_cadence: "cadence personnalisée",
    available_in_bloom: "disponible en version bloom",

    // Calendar sync
    calendar_sync_title: "synchronisation calendrier",
    calendar_sync_connected: "connecté",
    calendar_sync_disconnected: "non connecté",
    calendar_sync_connecting: "connexion en cours...",
    calendar_sync_connect_google: "connecter avec Google",
    calendar_sync_auto_label: "synchronisation automatique",
    calendar_sync_auto_desc: "ajoute tes habitudes à Google Calendar",
    calendar_sync_last: "dernière synchro",
    calendar_sync_now: "synchroniser maintenant",
    calendar_sync_disconnect: "déconnecter",

    // About
    about_title: "À propos de Bloom",
    about_mission_title: "Notre Mission",
    about_mission_text: "Chez Bloom, notre mission est de vous aider à cultiver des habitudes saines et à vous épanouir jour après jour. Nous croyons que de petits pas constants mènent à de grandes transformations.",
    about_version_title: "Version de l'application",

    // Journal mood labels
    mood_radiant: "radieux",
    mood_good: "bien",
    mood_neutral: "neutre",
    mood_hard: "difficile",
    mood_tough: "dur",
  },

  en: {
    // Navigation
    nav_dashboard: "home",
    nav_profile: "profile",
    nav_menu: "menu",
    nav_subscription: "subscription",
    nav_journal: "journal",
    nav_widgets: "widgets",

    // Dashboard
    petals: "petals",
    build_mode: "build mode",
    quit_mode: "quit mode",
    build_tagline: "build",
    quit_tagline: "break free",
    streak_days: "day streak",
    freed_days: "days free",
    hi_user: "Hi, {{name}}",
    dashboard_tagline: "Let's make habits together!",
    dashboard_tagline_quit: "Ready to break free?",
    dashboard_tagline_control: "Take back control!",
    dashboard_tagline_build: "Let's build tomorrow!",
    dashboard_quote: "Great journey. Your effort is legendary!",
    dashboard_suggested: "Suggested for You",
    dashboard_created_title: "Habits",
    dashboard_created_label: "created",
    dashboard_build_count_title: "Build",
    dashboard_build_count_label: "habits",
    dashboard_recent_title: "Recent Habits",
    daily_goals_title: "Your daily goals almost done! 🔥",
    daily_goals_subtitle: "{{completed}} of {{total}} completed",
    habits_title: "Habits",
    view_all: "View All",
    show_less: "Show Less",
    habit_done: "Done for today!",
    habit_not_started: "Not started yet",
    no_habits_yet: "No habits yet. Start small!",
    create_habit_cta: "+ Create a habit",
    done_today: "✓ done today",
    freed_day: "✓ free day",
    add_habit: "+ add a habit",
    add_habit_button: "Add a habit",
    no_habits: "No habits",
    partner_space: "Partner Space",
    upgrade_forever_desc: "Upgrade to Bloom Forever to remove ads 🌻",
    shield_activated: "Shield activated for 24h!",
    limit_reached: "Limit reached",
    seedling_limit_desc: "The free plan is limited to 3 simultaneous habits.",

    // Habit Calendar
    habit_calendar_title: "Habit Tracking",
    habits_of: "Habits for",
    no_habits_scheduled: "No habits scheduled for this day.",
    build_mode_label: "Build",
    quit_mode_label: "Quit",
    completed: "completed",

    // Habit Create/Edit
    habit_create_title: "New habit",
    habit_edit_title: "Edit habit",
    habit_type: "Type",
    habit_what: "What?",
    habit_quit_what: "Stop what?",
    habit_name_placeholder: "Meditate, Run...",
    habit_quit_placeholder: "Sugar, Smoking...",
    habit_frequency_time: "Frequency & Time",
    seedling_fixed: "Seedling (Fixed)",
    frequency_daily: "Daily",
    frequency_weekly: "Weekly",
    frequency_custom: "Custom",
    choose_days: "Choose days",
    reps_per_day: "Repetition / day",
    duration_min: "Duration (min)",
    reminder: "Reminder",
    end_habit_question: "End of habit?",
    by_date: "By date",
    by_count: "By count",
    total_executions: "total executions",
    reminder_message: "Reminder message",
    reminder_message_placeholder: "Ex: 'Don't forget to drink water!'",
    update_habit: "Update",
    save_habit: "Save habit",
    premium_feature: "Premium Feature",
    custom_cadence_locked_desc: "Custom rhythms are reserved for Bloom subscribers.",

    // Habit Detail
    current_level: "current level",
    timer: "timer",
    tip_of_the_day: "tip of the day",
    history: "history",
    stats: "stats",
    see_calendar: "see calendar",
    see_progress: "see your progress",
    no_habit_selected: "no habit selected",
    encourage_strong: "You hold a strong rhythm: {{streak}} days, {{effort}}.",
    encourage_steady: "Great consistency. Keep this {{effort}} up today.",
    encourage_start: "Small action now = real progress. Continue with a {{effort}}.",
    tips_build: [
      "start small: 2 minutes are better than 0 minutes",
      "do it at the same time every day to build a routine",
      "prepare your environment the night before to reduce friction",
      "stack this habit with an existing one (e.g., after coffee)",
      "celebrate every victory, even the tiny ones 🌻",
    ],
    tips_quit: [
      "identify the trigger that precedes the habit you want to quit",
      "replace the habit with something positive",
      "avoid environments that trigger cravings",
      "remind yourself why you want to quit (write it down)",
      "every day without relapse is a victory 💎",
    ],

    // Journal
    journal_title: "personal journal",
    journal_subtitle: "your thoughts, your space",
    new_entry: "new entry",
    today: "today",
    how_feeling: "how are you feeling today?",
    write_placeholder: "write here... no pressure, no judgment.",
    save_entry: "save",
    entries: "entries",
    no_entries: "no entries yet. start writing 🌱",
    edit_note: "Edit my note",
    write_first_thought: "Write my first thought",
    update_note: "Update",

    // Profile
    profile_title: "profile & history",
    your_journey: "your bloom journey",
    member_since: "member since May 2026",
    active_habits: "active habits",
    total_days: "total days",
    petals_count: "petals",
    year_activity: "year activity",
    less: "less",
    more: "more",
    insights: "insights",
    insights_desc: "Your trends and records",
    longest_streak: "longest streak",
    best_day: "best day",
    best_habit: "most successful habit",
    data_note: "💜 all your data is kept with care. even missed days stay visible to help you understand your journey.",
    days_label: ["m", "t", "w", "t", "f", "s", "s"],
    months_label: ["jan", "feb", "mar", "apr", "may", "jun", "jul", "aug", "sep", "oct", "nov", "dec"],
    settings_button: "settings",
    pass_pro: "Upgrade",
    logout: "Sign out",
    heatmap_locked_title: "Full Heatmap",
    heatmap_locked_desc: "Upgrade to Bloom to see your activity over the entire year.",
    unlock: "Unlock",
    unlock_insights: "Unlock Insights",

    // Settings Menu
    settings_menu_title: "Settings",
    menu_settings_title: "Settings",
    menu_settings_sub: "Themes, sounds and notifications",
    menu_journal_title: "Journal",
    menu_journal_sub: "Your thoughts, your space",
    menu_profile_title: "Profile & history",
    menu_profile_sub: "Your statistics and your journey",

    // Notifications
    notifications_title: "Notifications",
    notif_well_done: "Well done!",
    notif_its_time: "It's time!",
    notif_body_done: "You've completed your \"{{name}}\" goal for today.",
    notif_body_todo: "Don't forget to validate \"{{name}}\" to keep your {{streak}} day streak.",
    at_time: "at",
    no_notifications: "No notifications for now.",
    notif_build_title: "Time to build! 🌻",
    notif_quit_title: "Stay strong! 🕊️",
    notif_body_prefix: "It's time for: ",

    // Habit Validation Action
    error_oops: "Oops!",
    error_habit_not_found: "This habit no longer exists or has been deleted.",
    back_to_dashboard: "Back to dashboard",
    its_time: "It's time!",
    did_you_realize: "Did you realize your habit",
    ignore: "Ignore",
    validate: "Validate",
    habit_validated_success: "Great! {{name}} validated.",

    // Auth & Generic Errors
    error_all_fields_required: "Please fill in all fields.",
    error_passwords_mismatch: "Passwords do not match.",
    full_name_placeholder: "Full Name",

    // Calendar Sync
    features_title: "features",
    feature_1_title: "automatic events",
    feature_1_desc: "your daily habits are added to your calendar",
    feature_2_title: "synced reminders",
    feature_2_desc: "receive notifications at the right time",
    feature_3_title: "quick check-in",
    feature_3_desc: "mark habits as complete directly from Google Calendar",
    feature_4_title: "overview",
    feature_4_desc: "visualize all your habits at a glance",
    privacy_title: "your data stays private",
    privacy_desc: "bloom only accesses your calendar to add and update your habit events. we never read your other personal events.",

    // Check-in Modal
    daily_validation: "daily validation",
    bravo_for: "bravo for",
    how_feeling_today: "how are you feeling today?",
    personal_note_optional: "personal note (optional)",
    note_placeholder: "what did you feel? what did you learn?",
    validate_day: "validate the day",
    mood_excellent: "excellent",
    mood_good_label: "good",
    mood_neutral_label: "neutral",
    mood_hard_label: "hard",
    mood_struggling_label: "very hard",

    // Milestone Modal
    milestone_reached: "🎉 milestone reached!",
    milestone_7_msg: "Sunny is growing strong!",
    milestone_30_msg: "Sunny is FULLY bloomed. You did that!",
    milestone_100_msg: "Sunny is legendary now. Amazing.",
    milestone_default_msg: "Amazing! Keep it up.",
    dance_with_sunny: "dance with sunny!",
    share_success: "share my success",
    share_text: "{{streak}} day streak on Bloom! 🌻",

    // Widgets
    how_to_install: "How to install?",
    install_instructions: "Press and hold an empty area on your home screen, tap the **(+)** or **\"Widgets\"** button, and search for **Bloom**.",

    // Shield Modal
    bloom_shield_activated: "bloom shield activated",
    streak_protected: "streak protected",
    shield_modal_desc: "a crystal petal saved the day. streak protected. go rest — sunny's got this.",
    used_crystal_petal: "you used 1 crystal petal",
    thanks_sunny: "thanks sunny 💜",

    // Paywall
    paywall_title: "Bloom Plans",
    upgrade_title: "Level Up Your Bloom",
    upgrade_subtitle: "Release Sunny and unlock all capabilities",
    plan_seedling: "SEEDLING",
    plan_bloom: "BLOOM (Premium)",
    plan_forever: "BLOOM FOREVER",
    period_free: "free",
    period_monthly: "/ month (or $34.99/year)",
    period_once: "one-time payment",
    recommended: "Recommended",
    current_plan_label: "Current",
    version_current: "Current version",
    pass_to_bloom: "Upgrade to Bloom",
    become_founder: "Become a Founder",
    feature_limit_3: "Limited to 3 simultaneous habits",
    feature_basic_states: "Basic states (Neutral, Growing, Blooming)",
    feature_sunny_classic: "Home screen widget (Sunny Classic)",
    feature_basic_stats: "Basic statistics",
    feature_fixed_cadence: "Fixed cadence (Daily)",
    feature_ads_present: "Ad banners present",
    feature_unlimited_habits: "Unlimited number of habits",
    feature_7_states: "All 7 emotional states included",
    feature_all_widgets: "Home + Lock screen widgets",
    feature_full_heatmap: "Full heatmap & history",
    feature_custom_cadence: "Custom cadence (Weekly, etc.)",
    feature_no_ads: "Zero advertisements",
    feature_3_crystals: "+3 Crystals offered / month",
    feature_all_bloom: "All BLOOM plan features",
    feature_multiplier: "Petal multiplier x1.5",
    feature_skin_legend: "Exclusive \"Legend\" skin",
    feature_founder_badge: "Founder Badge",
    feature_lifetime: "Unlimited lifetime access",

    // Settings
    settings_title: "settings",
    appearance: "appearance",
    appearance_desc: "themes, sounds and animations",
    theme_system: "system",
    custom_colors: "custom colors",
    primary_color: "primary color",
    background_color: "background",
    text_color: "text",
    dark_mode: "dark mode",
    dark_mode_on: "deep night enabled",
    dark_mode_off: "sunbeam cream enabled",
    forest: "forest",
    ocean: "ocean",
    sound_effects: "sound effects",
    sound_effects_on_label: "on",
    sound_effects_off_label: "off",
    animations: "animations",
    animations_on_label: "on",
    animations_off_label: "off",
    notifications: "notifications",
    notif_examples: "examples of gentle reminders:",
    notif_example_1: "good morning. sunny's up and waiting — don't leave them on read.",
    notif_example_2: "hey, just a gentle reminder. sunny believes in you 🌻",
    notif_example_3: "you've built a great streak. come validate your day?",
    notif_toggle_desc: "turn gentle reminders on or off",
    integrations: "integrations",
    gcal: "Google Calendar",
    gcal_desc: "sync your habits with your calendar",
    account: "account",
    account_integrations: "account & integrations",
    account_integrations_desc: "subscription, export and calendar connection",
    manage_sub: "manage subscription",
    manage_sub_desc: "seedling version (free)",
    export_data: "export my data",
    export_data_desc: "download your history",
    about: "about bloom",
    version: "version 1.0.0",
    support: "support",
    support_desc: "help, contact and privacy",
    help_center: "help center",
    contact_us: "contact us",
    privacy: "privacy policy",
    language: "language",
    language_desc: "change the language without leaving the page",
    footer: "made with 💛 by the bloom team",
    bloom_premium: "bloom premium",
    premium_desc: "unlimited habits • 7 sunny emotions • zero ads",
    discover: "discover bloom",

    // Common
    back: "back",
    save: "save",
    cancel: "cancel",
    close: "close",

    // Onboarding
    onboarding_brand_step: "first step",
    onboarding_consent_title: "Your privacy, our priority.",
    onboarding_consent_subtitle: "To offer you the best Bloom experience, we need to collect some anonymous data.",
    onboarding_consent_cta: "I accept and continue",
    onboarding_consent_footer: "By continuing, you agree to Bloom's Terms of Service and Privacy Policy.",

    onboarding_welcome_hi_sunny: "Hi, I'm Sunny! 🌻",
    onboarding_welcome_subtext: "I'm so glad you're here. Let's grow something good together, one small habit at a time.",
    onboarding_welcome_cta: "Let's Bloom →",
    onboarding_welcome_already_account: "Already have an account?",
    onboarding_welcome_signin: "Sign in",

    onboarding_auth_title: "Let's get you set up",
    onboarding_auth_subtitle: "Choose how you’d like to continue. It only takes a moment.",
    onboarding_auth_apple: "Continue with Apple",
    onboarding_auth_google: "Continue with Google",
    onboarding_auth_facebook: "Continue with Facebook",
    onboarding_auth_email: "Continue with Email",
    onboarding_auth_sso: "Continue with SSO",
    onboarding_auth_footer: "Already have an account?",
    onboarding_auth_login: "Log in",
    onboarding_auth_safe: "Your info is safe with me. 💛",

    login_title: "Login",
    login_email_placeholder: "Email",
    login_password_placeholder: "Password",
    login_cta: "Sign In",
    login_forgot_password: "Forgot password?",
    login_privacy_terms: "By continuing, you agree to Bloom’s Terms of Service and Privacy Policy.",

    signup_title: "Create my account",
    signup_password_placeholder: "Password",
    signup_confirm_password_placeholder: "Confirm password",
    signup_cta: "Register",
    signup_consent_error: "You must accept the terms to continue.",

    survey_step1_title: "Let’s find your Bloom",
    survey_step2_title: "What habit type do you want to start with?",
    survey_step3_title: "How often do you want to check in on this habit?",
    survey_step1_sub: "A few quick questions so I can guide you the right way.",
    survey_step2_sub: "You can always add the other later.",
    survey_step3_sub: "Pick whatever feels doable, small and steady beats big and short-lived.",
    survey_step1_quote: "Whatever brought you here is a good enough reason.",
    survey_step2_quote: "A fresh start is waiting for you!",
    survey_step3_quote: "Small steps lead to big blooms!",
    survey_option_build_habits: "To build better daily habits",
    survey_option_break_habit: "To break free from a habit",
    survey_option_control: "To feel more in control",
    survey_option_explore: "Just exploring Bloom",
    survey_option_build_mode: "Build a good habit (Green mode)",
    survey_option_quit_mode: "Quit a bad habit (Purple mode)",
    survey_option_both: "A bit of both",
    survey_option_daily: "Daily",
    survey_option_often: "A few times a week",
    survey_option_weekly: "Weekly",
    survey_option_unsure: "I’m not sure yet",

    success_title: "You’re all set!",
    success_subtext: "I’ve got your first dashboard ready. Let’s take the first step, together.",
    success_cta: "Enter Bloom →",

    onboarding_intro_title: "Hello!",
    onboarding_intro_subtitle1: "My name is Sunny bloom.",
    onboarding_intro_subtitle2: "A gentle experience to track your habits, celebrate progress, and move at your own pace.",
    onboarding_intro_cta: "I start gently",
    onboarding_welcome_title: "hello, my name is sunny bloom.",
    onboarding_welcome_subtitle: "A gentle experience to track your habits, celebrate progress, and move at your own pace without pressure.",
    onboarding_mode_title: "let's get to know you a little",
    onboarding_mode_subtitle: "a few quick questions to suggest the best mode from the start.",
    onboarding_mode_question1: "You mainly want to...",
    onboarding_mode_question2: "The easiest rhythm for you is...",
    onboarding_mode_suggestion: "Our suggestion",
    onboarding_continue: "continue",
    onboarding_create_title: "create your first habit",
    onboarding_create_cta: "create and start",
    onboarding_back: "back",
    onboarding_mode_build: "Build",
    onboarding_mode_quit: "Quit",
    onboarding_mode_guided: "Guided",
    onboarding_mode_both: "Both",
    onboarding_mode_build_desc: "new habits",
    onboarding_mode_quit_desc: "bad habits",
    onboarding_mode_guided_desc: "a gentle start",
    onboarding_mode_both_desc: "depending on the day",
    onboarding_focus_small: "Small step",
    onboarding_focus_daily: "Every day",
    onboarding_focus_weekly: "Per week",
    onboarding_focus_small_desc: "1 action at a time",
    onboarding_focus_daily_desc: "a regular routine",
    onboarding_focus_weekly_desc: "broader goals",
    onboarding_suggest_guided: "Guided mode",
    onboarding_suggest_quit: "Quit mode",
    onboarding_suggest_build: "Build mode",
    onboarding_suggest_small: "We start light with one single priority.",
    onboarding_suggest_daily: "We set a simple routine to repeat daily.",
    onboarding_suggest_weekly: "We keep broader goals to track weekly.",

    // Onboarding Habit Specific
    habit_name_label: "habit name",
    habit_quit_label: "habit to quit",
    habit_name_ex: "ex: meditate for 10 minutes",
    habit_quit_ex: "ex: smoking",
    cadence: "cadence",
    daily: "daily",
    every_day: "every day",
    custom_cadence: "custom cadence",
    available_in_bloom: "available in bloom version",

    // Calendar sync
    calendar_sync_title: "calendar sync",
    calendar_sync_connected: "connected",
    calendar_sync_disconnected: "not connected",
    calendar_sync_connecting: "connecting...",
    calendar_sync_connect_google: "connect with Google",
    calendar_sync_auto_label: "automatic sync",
    calendar_sync_auto_desc: "adds your habits to Google Calendar",
    calendar_sync_last: "last sync",
    calendar_sync_now: "sync now",
    calendar_sync_disconnect: "disconnect",

    // About
    about_title: "About Bloom",
    about_mission_title: "Our Mission",
    about_mission_text: "At Bloom, our mission is to help you grow healthy habits and thrive day after day. We believe small consistent steps lead to meaningful transformation.",
    about_version_title: "App Version",

    // Journal mood labels
    mood_radiant: "radiant",
    mood_good: "good",
    mood_neutral: "neutral",
    mood_hard: "hard",
    mood_tough: "tough",
  },

  es: {
    // Navigation
    nav_dashboard: "inicio",
    nav_profile: "perfil",
    nav_menu: "menú",
    nav_subscription: "suscripción",
    nav_journal: "diario",
    nav_widgets: "widgets",

    // Dashboard
    petals: "pétalos",
    build_mode: "modo construcción",
    quit_mode: "modo abandono",
    build_tagline: "construye",
    quit_tagline: "libérate",
    streak_days: "días de racha",
    freed_days: "días libres",
    hi_user: "Hola, {{name}}",
    dashboard_tagline: "¡Hagamos hábitos juntos!",
    dashboard_tagline_quit: "¿Listo para liberarte?",
    dashboard_tagline_control: "¡Retoma el control!",
    dashboard_tagline_build: "¡Construyamos el mañana!",
    dashboard_quote: "Gran viaje. ¡Tu esfuerzo es legendario!",
    dashboard_suggested: "Sugerido para ti",
    dashboard_created_title: "Hábitos",
    dashboard_created_label: "creados",
    dashboard_build_count_title: "Construcción",
    dashboard_build_count_label: "hábitos",
    dashboard_recent_title: "Hábitos récentes",
    daily_goals_title: "¡Tus metas diarias casi están listas! 🔥",
    daily_goals_subtitle: "{{completed}} de {{total}} completados",
    habits_title: "Hábitos",
    view_all: "Ver todo",
    show_less: "Ver menos",
    habit_done: "¡Hecho por hoy!",
    habit_not_started: "Aún no ha comenzado",
    no_habits_yet: "Aún no hay hábitos. ¡Empieza pequeño!",
    create_habit_cta: "+ Crear un hábito",
    done_today: "✓ hecho hoy",
    freed_day: "✓ día libre",
    add_habit: "+ añadir hábito",
    add_habit_button: "Añadir un hábito",
    no_habits: "Sin hábitos",
    partner_space: "Espacio de Socios",
    upgrade_forever_desc: "Pásate a Bloom Forever para eliminar anuncios 🌻",
    shield_activated: "¡Escudo activado por 24h!",
    limit_reached: "Límite alcanzado",
    seedling_limit_desc: "El plan gratuito está limitado a 3 hábitos simultáneos.",

    // Habit Calendar
    habit_calendar_title: "Seguimiento de hábitos",
    habits_of: "Habitos de",
    no_habits_scheduled: "No hay hábitos programados para este día.",
    build_mode_label: "Construcción",
    quit_mode_label: "Abandono",
    completed: "completado",

    // Habit Create/Edit
    habit_create_title: "Nuevo hábito",
    habit_edit_title: "Editar hábito",
    habit_type: "Tipo",
    habit_what: "¿Qué?",
    habit_quit_what: "¿Dejar qué?",
    habit_name_placeholder: "Meditar, Correr...",
    habit_quit_placeholder: "Azúcar, Tabaco...",
    habit_frequency_time: "Frecuencia y tiempo",
    seedling_fixed: "Seedling (Fijo)",
    frequency_daily: "Diario",
    frequency_weekly: "Semanal",
    frequency_custom: "Personalizado",
    choose_days: "Elegir días",
    reps_per_day: "Repetición / día",
    duration_min: "Duración (min)",
    reminder: "Recordatorio",
    end_habit_question: "¿Fin del hábito?",
    by_date: "Por fecha",
    by_count: "Por número de veces",
    total_executions: "ejecuciones totales",
    reminder_message: "Mensaje de recordatorio",
    reminder_message_placeholder: "Ej: '¡No olvides beber agua!'",
    update_habit: "Actualizar",
    save_habit: "Guardar hábito",
    premium_feature: "Función Premium",
    custom_cadence_locked_desc: "Los ritmos personalizados están reservados para los suscriptores de Bloom.",

    // Habit Detail
    current_level: "nivel actual",
    timer: "temporizador",
    tip_of_the_day: "consejo del día",
    history: "historial",
    stats: "estadísticas",
    see_calendar: "ver el calendario",
    see_progress: "ver tu progreso",
    no_habit_selected: "ningún hábito seleccionado",
    encourage_strong: "Mantienes un ritmo fuerte: {{streak}} días, {{effort}}.",
    encourage_steady: "Gran constancia. Sigue este {{effort}} hoy.",
    encourage_start: "Acción pequeña ahora = progreso real. Continúa con un {{effort}}.",
    tips_build: [
      "empieza pequeño: 2 minutos son mejores que 0 minutos",
      "hazlo a la misma hora cada día para crear una rutina",
      "prepara tu entorno la noche anterior para reducir fricciones",
      "une este hábito a uno ya existente (ej: después del café)",
      "celebra cada victoria, incluso las más pequeñas 🌻",
    ],
    tips_quit: [
      "identifica el desencadenante que precede al hábito a dejar",
      "reemplaza el hábito por algo positivo",
      "evita los entornos que provocan el antojo",
      "recuérdate por qué quieres parar (escríbelo)",
      "cada día sin recaída es una victoria 💎",
    ],

    // Journal
    journal_title: "diario personal",
    journal_subtitle: "tus pensamientos, tu espace",
    new_entry: "nueva entrada",
    today: "hoy",
    how_feeling: "¿cómo te sientes hoy?",
    write_placeholder: "escribe aquí... sin presión, sin juicios.",
    save_entry: "guardar",
    entries: "entradas",
    no_entries: "aún no hay entradas. empieza a escribir 🌱",
    edit_note: "Editar mi nota",
    write_first_thought: "Escribir mi primer pensamiento",
    update_note: "Actualizar",

    // Profile
    profile_title: "perfil & historial",
    your_journey: "tu viaje bloom",
    member_since: "miembro desde mayo 2026",
    active_habits: "hábitos activos",
    total_days: "días totales",
    petals_count: "pétalos",
    year_activity: "actividad del año",
    less: "moins",
    more: "más",
    insights: "estadísticas",
    insights_desc: "Tus tendencias y récords",
    longest_streak: "racha más larga",
    best_day: "mejor día",
    best_habit: "hábito más exitoso",
    data_note: "💜 todos tus datos se guardan con cuidado. incluso los días perdidos son visibles para ayudarte a entender tu camino.",
    days_label: ["l", "m", "m", "j", "v", "s", "d"],
    months_label: ["ene", "feb", "mar", "abr", "may", "jun", "jul", "ago", "sep", "oct", "nov", "dic"],
    settings_button: "ajustes",
    pass_pro: "Mejorar",
    logout: "Cerrar sesión",
    heatmap_locked_title: "Heatmap completo",
    heatmap_locked_desc: "Pásate a Bloom para ver tu actividad durante todo el año.",
    unlock: "Desbloquear",
    unlock_insights: "Desbloquear Estadísticas",

    // Settings Menu
    settings_menu_title: "Ajustes",
    menu_settings_title: "Ajustes",
    menu_settings_sub: "Temas, sonidos y notificaciones",
    menu_journal_title: "Diario",
    menu_journal_sub: "Tus pensamientos, tu espacio",
    menu_profile_title: "Perfil e historial",
    menu_profile_sub: "Tus estadísticas y tu viaje",

    // Notifications
    notifications_title: "Notificaciones",
    notif_well_done: "¡Bien hecho!",
    notif_its_time: "¡Es la hora!",
    notif_body_done: "Has completado tu objetivo \"{{name}}\" por hoy.",
    notif_body_todo: "No olvides validar \"{{name}}\" para mantener tu racha de {{streak}} días.",
    at_time: "a las",
    no_notifications: "No hay notificaciones por ahora.",
    notif_build_title: "¡Es hora de construir! 🌻",
    notif_quit_title: "¡Mantente fuerte! 🕊️",
    notif_body_prefix: "Es momento de: ",

    // Habit Validation Action
    error_oops: "¡Ups!",
    error_habit_not_found: "Este hábito ya no existe o ha sido eliminado.",
    back_to_dashboard: "Volver al tablero",
    its_time: "¡Es la hora!",
    did_you_realize: "¿Has realizado tu hábito?",
    ignore: "Ignorar",
    validate: "Validar",
    habit_validated_success: "¡Genial! {{name}} validado.",

    // Auth & Generic Errors
    error_all_fields_required: "Por favor, complete todos los campos.",
    error_passwords_mismatch: "Las contraseñas no coinciden.",
    full_name_placeholder: "Nombre completo",

    // Calendar Sync
    features_title: "características",
    feature_1_title: "eventos automáticos",
    feature_1_desc: "tus hábitos diarios se añaden a tu calendario",
    feature_2_title: "recordatorios sincronizados",
    feature_2_desc: "recibe notificaciones en el momento adecuado",
    feature_3_title: "check-in rápido",
    feature_3_desc: "marca tus hábitos como completados directamente desde Google Calendar",
    feature_4_title: "vista general",
    feature_4_desc: "visualiza todos tus hábitos de un vistazo",
    privacy_title: "tus datos permanecen privados",
    privacy_desc: "bloom solo accede a tu calendario para añadir y actualizar tus eventos de hábitos. nunca leemos tus otros eventos personales.",

    // Check-in Modal
    daily_validation: "validación diaria",
    bravo_for: "bravo por",
    how_feeling_today: "¿cómo te sientes hoy?",
    personal_note_optional: "nota personal (opcional)",
    note_placeholder: "¿qué has sentido? ¿qué has aprendido?",
    validate_day: "validar el día",
    mood_excellent: "excelente",
    mood_good_label: "bien",
    mood_neutral_label: "neutral",
    mood_hard_label: "difícil",
    mood_struggling_label: "muy difícil",

    // Milestone Modal
    milestone_reached: "🎉 ¡jalón alcanzado!",
    milestone_7_msg: "¡Sunny se vuelve cada vez más fuerte!",
    milestone_30_msg: "Sunny está en PLENA floración. ¡Lo hiciste!",
    milestone_100_msg: "Sunny es legendario ahora. Increíble.",
    milestone_default_msg: "¡Increíble! Sigue así.",
    dance_with_sunny: "¡bailar con sunny!",
    share_success: "compartir mi éxito",
    share_text: "¡{{streak}} días de racha en Bloom! 🌻",

    // Widgets
    how_to_install: "¿Cómo instalar?",
    install_instructions: "Mantén pulsada una zona vacía de tu pantalla de inicio, toca el botón **(+)** o **\"Widgets\"** y busca **Bloom**.",

    // Shield Modal
    bloom_shield_activated: "bloom shield activado",
    streak_protected: "racha protegida",
    shield_modal_desc: "un pétalo de cristal salvó el día. racha protegida. ve a descansar — sunny se encarga.",
    used_crystal_petal: "has usado 1 pétalo de cristal",
    thanks_sunny: "gracias sunny 💜",

    // Paywall
    paywall_title: "Planes Bloom",
    upgrade_title: "Mejora tu Bloom",
    upgrade_subtitle: "Libera a Sunny y desbloquea todas tus capacidades",
    plan_seedling: "SEEDLING",
    plan_bloom: "BLOOM (Premium)",
    plan_forever: "BLOOM FOREVER",
    period_free: "gratis",
    period_monthly: "/ mes (o 34.99$/año)",
    period_once: "pago único",
    recommended: "Recomendado",
    current_plan_label: "Actual",
    version_current: "Versión actual",
    pass_to_bloom: "Mejorar a Bloom",
    become_founder: "Convertirse en Fundador",
    feature_limit_3: "Limitado a 3 hábitos simultáneos",
    feature_basic_states: "Estados básicos (Neutral, Growing, Blooming)",
    feature_sunny_classic: "Widget de pantalla de inicio (Sunny Classic)",
    feature_basic_stats: "Estadísticas elementales",
    feature_fixed_cadence: "Cadencia fija (Diaria)",
    feature_ads_present: "Banners publicitarios presentes",
    feature_unlimited_habits: "Número de hábitos ilimitado",
    feature_7_states: "Los 7 estados emocionales incluidos",
    feature_all_widgets: "Widgets de inicio + bloqueo",
    feature_full_heatmap: "Heatmap completo e historial",
    feature_custom_cadence: "Cadencia personalizada (Semanal, etc.)",
    feature_no_ads: "Sin publicidad",
    feature_3_crystals: "+3 Cristales ofrecidos / mes",
    feature_all_bloom: "Todo el plan BLOOM",
    feature_multiplier: "Multiplicador de pétalos x1.5",
    feature_skin_legend: "Skin exclusiva \"Legend\"",
    feature_founder_badge: "Badge de Fundador",
    feature_lifetime: "Acceso ilimitado de por vida",

    // Settings
    settings_title: "ajustes",
    appearance: "appariencia",
    appearance_desc: "temas, sonidos et animaciones",
    theme_system: "sistema",
    custom_colors: "colores personalizados",
    primary_color: "color principal",
    background_color: "fondo",
    text_color: "texto",
    dark_mode: "modo oscuro",
    dark_mode_on: "noche profunda activado",
    dark_mode_off: "crema sunbeam activado",
    forest: "forêt",
    ocean: "océano",
    sound_effects: "efectos de sonido",
    sound_effects_on_label: "activados",
    sound_effects_off_label: "desactivados",
    animations: "animaciones",
    animations_on_label: "activadas",
    animations_off_label: "desactivadas",
    notifications: "notifications",
    notif_examples: "ejemplos de recordatorios amables:",
    notif_example_1: "good morning. sunny's up and waiting — don't leave them on read.",
    notif_example_2: "hey, solo un recordatorio amable. sunny cree en ti 🌻",
    notif_example_3: "has construido una gran racha. ¿vienes a validar tu día?",
    notif_toggle_desc: "activa o desactiva los recordatorios amables",
    integrations: "integrations",
    gcal: "Google Calendar",
    gcal_desc: "sincroniza tus hábitos con tu calendario",
    account: "cuenta",
    account_integrations: "cuenta e integraciones",
    account_integrations_desc: "suscripción, exportación y conexión al calendario",
    manage_sub: "gestionar suscripción",
    manage_sub_desc: "versión seedling (gratuite)",
    export_data: "exportar mis datos",
    export_data_desc: "descarga tu historial",
    about: "sobre bloom",
    version: "versión 1.0.0",
    support: "soporte",
    support_desc: "ayuda, contacto y privacidad",
    help_center: "centro de ayuda",
    contact_us: "contáctanos",
    privacy: "política de privacidad",
    language: "idioma",
    language_desc: "cambia el idioma sin salir de la página",
    footer: "fait avec 💛 par l'équipe bloom",
    bloom_premium: "bloom premium",
    premium_desc: "hábitos ilimitados • 7 emociones de sunny • sin anuncios",
    discover: "descubrir bloom",

    // Common
    back: "volver",
    save: "guardar",
    cancel: "cancelar",
    close: "cerrar",

    // Onboarding
    onboarding_brand_step: "primer paso",
    onboarding_consent_title: "Tu privacidad, nuestra prioridad.",
    onboarding_consent_subtitle: "Para ofrecerte la mejor experiencia Bloom, necesitamos recopilar algunos datos anónimos.",
    onboarding_consent_cta: "Acepto y continúo",
    onboarding_consent_footer: "Al continuar, aceptas las Condiciones de servicio y la Política de privacidad de Bloom.",

    onboarding_welcome_hi_sunny: "¡Hola, soy Sunny! 🌻",
    onboarding_welcome_subtext: "Estoy muy feliz de que estés aquí. Cultivemos algo bueno juntos, un pequeño hábito a la vez.",
    onboarding_welcome_cta: "¡Vamos! →",
    onboarding_welcome_already_account: "¿Ya tienes una cuenta?",
    onboarding_welcome_signin: "Iniciar sesión",

    onboarding_auth_title: "Preparemos tu llegada",
    onboarding_auth_subtitle: "Elige cómo deseas continuar. Solo toma un momento.",
    onboarding_auth_apple: "Continuar con Apple",
    onboarding_auth_google: "Continuar con Google",
    onboarding_auth_facebook: "Continuar con Facebook",
    onboarding_auth_email: "Continuar con Email",
    onboarding_auth_sso: "Continuar con SSO",
    onboarding_auth_footer: "¿Ya tienes una cuenta?",
    onboarding_auth_login: "Iniciar sesión",
    onboarding_auth_safe: "Tu información está segura conmigo. 💛",

    login_title: "Conexión",
    login_email_placeholder: "Correo electrónico",
    login_password_placeholder: "Contraseña",
    login_cta: "Iniciar sesión",
    login_forgot_password: "¿Has olvidado tu contraseña?",
    login_privacy_terms: "Al continuar, aceptas las Condiciones de servicio y la Política de privacidad de Bloom.",

    signup_title: "Crear mi cuenta",
    signup_password_placeholder: "Contraseña",
    signup_confirm_password_placeholder: "Confirmar contraseña",
    signup_cta: "Registrarse",
    signup_consent_error: "Debes aceptar los términos para continuar.",

    survey_step1_title: "Encontremos tu Bloom",
    survey_step2_title: "¿Con qué tipo de hábito quieres empezar?",
    survey_step3_title: "¿Con qué frecuencia quieres seguir este hábito?",
    survey_step1_sub: "Unas preguntas rápidas para que pueda guiarte lo mejor posible.",
    survey_step2_sub: "Siempre podrás añadir el otro más tarde.",
    survey_step3_sub: "Elige lo que te parezca factible, la constancia supera a la intensidad.",
    survey_step1_quote: "No importa lo que te traiga aquí, es una excelente razón.",
    survey_step2_quote: "¡Un nuevo comienzo te espera!",
    survey_step3_quote: "¡Los pequeños pasos llevan a grandes floraciones!",
    survey_option_build_habits: "Crear mejores hábitos",
    survey_option_break_habit: "Liberarse de un hábito",
    survey_option_control: "Sentirme más en control",
    survey_option_explore: "Solo explorar Bloom",
    survey_option_build_mode: "Crear un buen hábito (Modo Verde)",
    survey_option_quit_mode: "Dejar un mal hábito (Modo Morado)",
    survey_option_both: "Un peu de ambos",
    survey_option_daily: "Diario",
    survey_option_often: "Unas veces por semana",
    survey_option_weekly: "Semanal",
    survey_option_unsure: "Aún no lo sé",

    success_title: "¡Todo listo!",
    success_subtext: "Tu primer panel de control está listo. Demos el primer paso juntos.",
    success_cta: "Entrar en Bloom →",

    onboarding_intro_title: "¡Hola!",
    onboarding_intro_subtitle1: "Me llamo Sunny bloom.",
    onboarding_intro_subtitle2: "Una expérience suave para seguir tus hábitos, celebrar avances y avanzar a tu ritmo.",
    onboarding_intro_cta: "Empiezo suave",
    onboarding_welcome_title: "hola, me llamo sunny bloom.",
    onboarding_welcome_subtitle: "Una experiencia suave para seguir tus hábitos, celebrar avances y avanzar a tu ritmo sin presión.",
    onboarding_mode_title: "vamos a conocerte un poco",
    onboarding_mode_subtitle: "unas preguntas rápidas para sugerirte el mejor modo desde el inicio.",
    onboarding_mode_question1: "Sobre todo quieres...",
    onboarding_mode_question2: "Lo más facile para ti es...",
    onboarding_mode_suggestion: "Nuestra sugerencia",
    onboarding_continue: "continuar",
    onboarding_create_title: "crea tu primer hábito",
    onboarding_create_cta: "crear y empezar",
    onboarding_back: "volver",
    onboarding_mode_build: "Construire",
    onboarding_mode_quit: "Dejar",
    onboarding_mode_guided: "Guiado",
    onboarding_mode_both: "Ambos",
    onboarding_mode_build_desc: "new habits",
    onboarding_mode_quit_desc: "bad habits",
    onboarding_mode_guided_desc: "inicio suave",
    onboarding_mode_both_desc: "según el día",
    onboarding_focus_small: "Paso pequeño",
    onboarding_focus_daily: "Cada día",
    onboarding_focus_weekly: "Por semana",
    onboarding_focus_small_desc: "1 action a la vez",
    onboarding_focus_daily_desc: "rutina regular",
    onboarding_focus_weekly_desc: "objetivos más amplios",
    onboarding_suggest_guided: "Modo guiado",
    onboarding_suggest_quit: "Modo dejar",
    onboarding_suggest_build: "Modo construir",
    onboarding_suggest_small: "Empezamos ligero con una sola priorité.",
    onboarding_suggest_daily: "Planteamos una rutina simple para repetir cada día.",
    onboarding_suggest_weekly: "Mantenemos objetivos más amplios para seguir cada semana.",

    // Onboarding Habit Specific
    habit_name_label: "nombre del hábito",
    habit_quit_label: "hábito a dejar",
    habit_name_ex: "ej: meditar 10 minutos",
    habit_quit_ex: "ej: fumar",
    cadence: "cadencia",
    daily: "diaria",
    every_day: "todos los días",
    custom_cadence: "cadencia personalizada",
    available_in_bloom: "disponible en versión bloom",

    // Calendar sync
    calendar_sync_title: "sincronización de calendario",
    calendar_sync_connected: "conectado",
    calendar_sync_disconnected: "no conectado",
    calendar_sync_connecting: "conectando...",
    calendar_sync_connect_google: "conectar con Google",
    calendar_sync_auto_label: "sincronización automática",
    calendar_sync_auto_desc: "añade tus hábitos a Google Calendar",
    calendar_sync_last: "última sincronización",
    calendar_sync_now: "sincronizar ahora",
    calendar_sync_disconnect: "desconectar",

    // About
    about_title: "Acerca de Bloom",
    about_mission_title: "Nuestra misión",
    about_mission_text: "En Bloom, nuestra misión es ayudarte a cultivar hábitos saludables y crecer día tras día. Creemos que los pequeños pasos constantes generan grandes cambios.",
    about_version_title: "Versión de la aplicación",

    // Journal mood labels
    mood_radiant: "radiante",
    mood_good: "bien",
    mood_neutral: "neutral",
    mood_hard: "diffícil",
    mood_tough: "duro",
  },
} as const;

type TranslationKeys = keyof typeof translations.fr;

interface LanguageContextType {
  lang: Language;
  setLang: (l: Language) => void;
  t: (key: TranslationKeys) => string | readonly string[];
}

const LanguageContext = createContext<LanguageContextType | null>(null);

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [lang, setLangState] = useState<Language>(() => {
    if (typeof window !== "undefined") {
      return (localStorage.getItem("bloom_lang") as Language) || "fr";
    }
    return "fr";
  });

  const setLang = (l: Language) => {
    localStorage.setItem("bloom_lang", l);
    setLangState(l);
  };

  const t = (key: TranslationKeys): string | readonly string[] => {
    return (translations[lang] as Record<string, string | readonly string[]>)[key] ?? key;
  };

  return (
    <LanguageContext.Provider value={{ lang, setLang, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const ctx = useContext(LanguageContext);
  if (!ctx) throw new Error("useLanguage must be used inside LanguageProvider");
  return ctx;
}
