from typing import Any

class Connection:
    async def execute(self, query: str, *args: Any) -> Any: ...
    async def fetch(self, query: str, *args: Any) -> list[Any]: ...
    async def fetchrow(self, query: str, *args: Any) -> Any: ...
    def transaction(self) -> Any: ...

class Pool:
    def acquire(self) -> Any: ...
    async def close(self) -> None: ...

async def create_pool(*args: Any, **kwargs: Any) -> Pool: ...
